---
# Source: health-check/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: health-check
  labels:
    app: health-check
    release: health-check
spec:
  replicas: 1
  selector:
    matchLabels:
      app: health-check
      release: health-check
  template:
    metadata:
      labels:
        app: health-check
        release: health-check
    spec:
      containers:
      - name: health-check
        image: "yadyedida/health-check:latest"
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        resources:
          requests:
            memory: 64Mi
            cpu: 250m
          limits:
            memory: 128Mi
            cpu: 500m
        startupProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 5
          failureThreshold: 5
          periodSeconds: 10
        livenessProbe:
          httpGet:
            path: /liveness
            port: 8080
          initialDelaySeconds: 5
          failureThreshold: 5
          periodSeconds: 10
      nodeSelector: 
      tolerations: []
