---
# Source: health-check/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: health-check
  labels:
    app: health-check
    release: health-check
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 
      nodePort: 
  selector:
    app: health-check
    release: health-check
