replicaCount: 2

image:
  repository: yadyedida/health-check
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8080

resources:
  requests:
    memory: "64Mi"
    cpu: "250m"
  limits:
    memory: "128Mi"
    cpu: "500m"

podAnnotations: {}
tolerations: []
affinity: {}